---
title: |
    | _Ecology_: Data Paper 
    | **Demography of the understory herb _Heliconia acuminata_ (Heliconiaceae) in an experimentally fragmented tropical landscape**
shorttitle        : "Tropical plant demography"
author: 
  - name          : "Emilio M. Bruna"
    affiliation   : "1,2,3"
    address       : "Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, FL 32611-0430, USA"
    email         : "embruna@ufl.edu"
    role:
      - Methodology
      - Data curation
      - Investigation
      - Funding acquisition
      - Conceptualization
      - Formal analysis
      - Methodology
      - Project administration
      - Resources
      - Software
      - Supervision
      - Validation
      - Visualization
      - Writing – original draft
    corresponding : yes
  - name          : "Maria Uriarte"
    affiliation   : "4"
    role:
      - Methodology
      - Investigation
      - Funding acquisition
      - Conceptualization
      - Formal analysis
      - Methodology
      - Project administration
      - Resources
      - Software
      - Supervision
      - Validation
      - Visualization
      - Writing – review & editing
      
  - name          : "Maria Rosa Darrigo"
    affiliation   : "3"
    role:
      - Methodology
      - Investigation
      - Project administration
      - Writing – review & editing
  - name          : "Paulo Rubim"
    affiliation   : "3"
    role: 
      - Methodology
      - Investigation
      - Project administration
      - Writing – review & editing
  - name          : "Cristiane F. Jurinitz"
    affiliation   : "3"
    role: 
      - Methodology
      - Investigation
      - Project administration
      - Writing – review & editing
  - name          : "Eric R. Scott"
    affiliation   : "1"
    # affiliation   : "1,*"
    role:
      - Methodology
      - Data curation
      - Software
      - Validation
      - Visualization
      - Writing – review & editing
  - name          : "Osmaildo Ferreira da Silva"
    affiliation   : "3"
    role: 
      - Investigation
      - Project administration
  - name        : "W. John Kress"
    affiliation : "5"
    role:
      - Methodology
      - Investigation
      - Funding acquisition
      - Conceptualization
      - Methodology
      - Resources
      - Writing – review & editing
affiliation:
  - id            : "1"
    institution   : "Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, FL 32611-0430, USA"
  - id            : "2"
    institution   : "Center for Latin American Studies, University of Florida, PO Box 115530, Gainesville, FL 32611-5530, USA"
  - id            : "3"
    institution   : "Biological Dynamics of Forest Fragments Project, INPA-PDBFF, CP 478, Manaus, AM 69011-970, Brazil"
  - id            : "4"
    institution   : "Department of Ecology, Evolution and Environmental Biology, Columbia University, 1200 Amsterdam Ave., New York, New York 10027, USA"
  - id            : "5"
    institution   : "Department of Botany, National Museum of Natural History, PO Box 37012, Smithsonian Institution, PO Box 37012, Washington DC, USA"
  # - id            : "*"
  #   institution   : "Current Address: ---, University of Arizona, Pheonix, AZ ZIP CODE, USA"

# Note /par in abstratc is to inster a paragraph break
abstract: |
  \par Habitat fragmentation remains a major focus of research by ecologists decades after being put forward as a threat to the integrity of ecosystems. While studies have documented myriad biotic changes in fragmented landscapes, including the local extinction of species from fragments, the demographic mechanisms underlying these extinctions are rarely known. However, many of them – especially in lowland tropical forests – are thought to be driven by one of two mechanisms: (1) reduced recruitment in fragments resulting from changes in the diversity or abundance of pollinators and seed dispersers or (2) increased rates of individual mortality in fragments due to dramatically altered abiotic conditions, especially near fragment edges. Unfortunately, there have been few tests of these potential mechanisms due to the paucity of long-term and comprehensive demographic data collected in both forest fragments and continuous forest sites. Here we report 11 years (1998-2009) of demographic data from populations of the Amazonian understory herb _Heliconia acuminata_ (LC Rich.) found at Brazil's Biological Dynamics of Forest Fragments Project (BDFFP). The dataset comprises >66,000 plant$\times$year records of 8586 plants, including 3464 seedlings established after the first census. Seven populations were in experimentally isolated fragments (one in each of four 1-ha fragments and one in each of three 10-ha fragments), with the remaining six populations in continuous forest. Each population was in a $50\times100$m permanent plot, with the distance between plots ranging from 500 m-60 km. The plants in each plot were censused annually, at which time we recorded, identified, marked, and measured new seedlings, identified any previously marked plants that died, and recorded the size of surviving individuals. Each plot was also surveyed 4-5 times during the flowering season to identify reproductive plants and record the number of inflorescences each produced. These data have been used to investigate topics ranging from the way fragmentation-related reductions in germination influence population dynamics to statistical methods for analyzing reproductive rates. This breadth of prior use reflects the value of these data to future researchers. In addition to analyses of plant responses to habitat fragmentation, these data can be used to address fundamental questions in plant demography, the evolutionary ecology of tropical plants, and for developing and testing demographic models and tools. Though we welcome opportunities to collaborate with interested users, there are no restrictions on the use this data set. However, we do request that those using the data for teaching or research inform us of how they are doing so and cite this paper and the data archive when appropriate. Any publication using the data must also include a BDFFP Technical Series Number in the Acknowledgments. Authors can request this series number upon the acceptance of their article by contacting the BDFFP's Scientific Coordinator or E. M. Bruna.  
  
# 
#   text
# 
note: | 
    
    _Corresponding author_: Emilio M. Bruna (embruna@ufl.edu)  
    _Open Research Statement_: The data described here have are available as Supporting Information at [_url to be added_] and have been archived at the Dryad Digital Repository [_url to be added_]. The version of the code used to review, correct, and prepare this archive is at Zenodo [_url to be added_]. The code used to prepare this manuscript -- including statistical summaries, tables, and figures -- has also been archived at Zenodo [_url to be added_]. Post-publication updates to code and the data sets, along with other project-related information, can be found at the [HDP Github Repository](https://github.com/BrunaLab/HeliconiaSurveys).
    _Conflict of interest Statement_: The authors declare no conflict of interest.

    
  

# wordcount: "4824"
  
# authornote: |
#     
#     _Conflict of interest Statement_: The authors declare no conflict of interest.
#   
#     _Corresponding author_: Emilio M. Bruna (embruna@ufl.edu)
# _Word count_: 4824 (text), 1734 (references)
  
      



keywords: "Amazon, Brazil, deforestation, demography, edge effects, forest fragments, habitat fragmentation, integral projection models, matrix models, population dynamics, vital rates"
# 

floatsintext      : no
figurelist        : yes
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
documentclass     : "apa6"
# classoption       : "man"
classoption       : "man, donotrepeattitle" # suppresses title on 1st page of MS
output: papaja::apa6_pdf
# output: papaja::apa6_word
  # papaja::apa6_pdf:
#     latex_engine: xelatex
mainfont: Times New Roman
fontsize: 12pt
# output: 
  # papaja::apa6_pdf:
  # keep_tex: true   
# output:
#   papaja::apa6_pdf:
#     includes:
#       after_body: "appendix.tex"
# appendix: "Appendix.Rmd"
# appendix: "Bruna_etal_s1_plots.Rmd"
bibliography: ["../references.bib"] 
#.// indicates it is in the parent directory (used for both ms and appendix)
csl: "../ecology.csl"
fig_caption: yes #yes will automatically add "Figure X" to the start 
always_allow_html: yes
header-includes:
  - \usepackage{booktabs}
  - \raggedbottom
 # - \usepackage{endfloat} #[nomarkers] excludes the {insert figure x around here] from main text. The others exclude the list of tables and figures. https://cs.brown.edu/about/system/managed/latex/doc/endfloat.pdf
  - \usepackage{tabu}
  - \usepackage{pdflscape}
  - \usepackage{longtable}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \setlength\parindent{22pt}



editor_options: 
  markdown: 
    wrap: 72
---

```{r GlobalOptions}
options(knitr.duplicate.label = 'allow')
```

```{r setup, include = FALSE}
library("papaja")
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(gridExtra)
library(kableExtra)
library(knitr)
library(cowplot)
# library(egg)
library(magick)
library(citr)
# library(devtools)
# devtools::install_github("crsh/papaja")
```

<!-- ```{r data_load, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE} -->
<!-- # knitr::opts_chunk$set(echo = FALSE) -->

<!-- urlfile_plants<-("https://raw.githubusercontent.com/BrunaLab/HeliconiaSurveys/master/data_clean/HDP_1998_2009.csv") -->
<!-- ha_plants<-read_csv(url(urlfile_plants)) -->

<!-- urlfile_plots<-"https://raw.githubusercontent.com/BrunaLab/HeliconiaSurveys/master/data_clean/HDP_plots.csv" -->
<!-- ha_plots<-read_csv(url(urlfile_plots)) -->

<!-- ``` -->


<!-- ```{r GlobalOptions, include=FALSE} -->
<!-- options(knitr.duplicate.label = 'allow') -->
<!-- knitr::opts_chunk$set(fig.pos = 'h') -->
<!-- ``` -->

<!-- ```{r setup, include = FALSE} -->
<!-- library("papaja") -->
<!-- knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE) -->
<!-- library(tidyverse) -->
<!-- library(gridExtra) -->
<!-- library(kableExtra) -->
<!-- library(knitr) -->
<!-- library(cowplot) -->
<!-- # library(egg) -->
<!-- library(magick) -->
<!-- library(citr) -->
<!-- # library(devtools) -->
<!-- # devtools::install_github("crsh/papaja") -->
<!-- ``` -->

<!-- ```{r data_load, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE} -->
<!-- # knitr::opts_chunk$set(echo = FALSE) -->

<!-- urlfile_plants<-("https://raw.githubusercontent.com/BrunaLab/HeliconiaSurveys/master/data/survey_archive/HDP_survey.csv") -->
<!-- ha_plants<-read_csv(url(urlfile_plants)) -->

<!-- urlfile_plots<-"https://raw.githubusercontent.com/BrunaLab/HeliconiaSurveys/master/data/survey_archive/HDP_plots.csv" -->
<!-- ha_plots<-read_csv(url(urlfile_plots)) -->

<!-- # This is to save the info on the version of the data sets used in the paper  -->
<!-- urlfile_v_plots<-"https://raw.githubusercontent.com/BrunaLab/HeliconiaSurveys/master/data/survey_archive/HDP_plots_version_info.txt" -->
<!-- version_plots<-read_lines(url(urlfile_v_plots)) -->

<!-- urlfile_v_survey<-"https://raw.githubusercontent.com/BrunaLab/HeliconiaSurveys/master/data/survey_archive/HDP_survey_version_info.txt" -->
<!-- version_survey<-read_lines(url(urlfile_v_survey)) -->

<!-- version_survey$file<-"survey" -->
<!-- names(version_survey)<-c("version", "date", "file") -->
<!-- version_plots$file<-"plots" -->
<!-- names(version_plots)<-c("version", "date", "file") -->
<!-- versions_for_ms<-bind_rows(as_tibble(version_survey), -->
<!--                            as_tibble(version_plots)) %>%  -->
<!--   relocate(file,.before=1) -->
<!-- write_csv(versions_for_ms,"./MetadataS1/versions_for_ms.csv") -->



<!-- # these data were for a pilot study on self-fertilization and are useful records of number fof flowers, fruits, etc. -->
<!-- urlfile_reprodata2<-paste0("https://raw.githubusercontent.com/BrunaLab/Hacuminata_leaf_shoot_height_data/master/data_clean/ha_size_data_1998_cor.csv") -->
<!-- ha_repro2<-read_csv(url(urlfile_reprodata2)) -->


<!-- ``` -->




<!-- ```{r plot_file_info, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE} -->

<!-- # Function to find size of the file -->
<!-- library(rvest) -->

<!-- plot_url<-paste0("https://github.com/BrunaLab/HeliconiaSurveys/", -->
<!--             "blob/9d56950ae221911dc90e4826c1fbb8f46c62b659/", -->
<!--             "data/survey_archive/HDP_plots.csv") -->
<!--   plot_page <- read_html(plot_url) -->

<!--   plot_file <- tail(strsplit(plot_url, "/")[[1]], 1) -->
<!--   plot_div1 <- "text-mono f6 flex-auto pr-3 flex-order-2 flex-md-order-1" -->


<!--   file_plots_size <- plot_page %>% -->
<!--     html_elements(xpath = paste0("//div[@class='", plot_div1, "']")) %>% -->
<!--     html_text() %>% -->
<!--     strsplit("\n") %>% -->
<!--     sapply(trimws) %>% -->
<!--     getElement(5) -->
<!--   # file_plots_size -->

<!--   # file_plots_date <- plot_page %>% -->
<!--   #   html_elements(xpath = '//*[@id="repo-content-pjax-container"]') %>% -->
<!--   #   # html_text() %>% -->
<!--   #   # strsplit("\n") %>% -->
<!--   #   # sapply(trimws) -->
<!--   #   html_elements("relative-time") %>% -->
<!--   #   html_attr("datetime") %>% -->
<!--   #   as.POSIXct() -->
<!--   # file_plots_date -->


<!-- rm(plot_url) -->
<!-- rm(plot_page) -->
<!-- rm(plot_file) -->
<!-- rm(plot_div1) -->

<!-- # ha_plots <- read_csv("./survey_clean/HDP_plots.csv", col_types = cols()) -->
<!-- # Number of rows in the survey file -->
<!-- file_plots_rows <- nrow(ha_plots)+1  -->

<!-- ``` -->
<!-- ```{r plants_file_size, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE} -->

<!--  # Function to find size of the file -->
<!--  library(rvest) -->

<!--  plant_url<-paste0("https://github.com/BrunaLab/HeliconiaSurveys/", -->
<!--                    "blob/9d56950ae221911dc90e4826c1fbb8f46c62b659/", -->
<!--                    "data/survey_archive/HDP_survey.csv") -->

<!--    plant_page <- read_html(plant_url) -->

<!--    plant_file <- tail(strsplit(plant_url, "/")[[1]], 1) -->
<!--    plant_div1 <- "text-mono f6 flex-auto pr-3 flex-order-2 flex-md-order-1" -->


<!--    file_plants_size <- plant_page %>% -->
<!--      html_elements(xpath = paste0("//div[@class='", plant_div1, "']")) %>% -->
<!--      html_text() %>% -->
<!--      strsplit("\n") %>% -->
<!--      sapply(trimws) %>% -->
<!--      getElement(3) -->
<!--    # file_plants_size -->

<!--    # file_plants_date <- plant_page %>% -->
<!--    #  html_elements(xpath = '//*[@id="repo-content-pjax-container"]') %>% -->
<!--    #   html_elements("relative-time") %>% -->
<!--    #   html_attr("datetime") %>% -->
<!--    #   as.POSIXct() -->
<!--    # file_plants_date -->


<!-- #  data on flowering and fruiting -->
<!--    # file_plants_date -->



<!--  rm(plant_url) -->
<!--  rm(plant_page) -->
<!--  rm(plant_file) -->
<!--  rm(plant_div1) -->

<!--  # No of rows in the file -->
<!--  file_plants_rows <- nrow(ha_plants)+1 # Need to add one for the header -->

<!-- ``` -->
<!-- ```{r cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE} -->

<!-- nplants <- ha_plants %>% -->
<!--   summarize(n=n_distinct(plant_id)) -->

<!-- nsdlgs <- ha_plants %>% -->
<!--   filter(recorded_sdlg=="TRUE") %>%  -->
<!--   tally() -->

<!-- nrows<-nrow(ha_plants) -->

<!-- ``` -->
